name: example
description: "Liquido Examples App - Showcasing usage example on flutter"
publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  mesh: ^0.5.0
  liquido: 
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


